export const jobLocations = [
  { value: "Mumbai", label: "Mumbai" },
  { value: "Pune", label: "Pune" },
  { value: "Nagpur", label: "Nagpur" },
  { value: "Nashik", label: "Nashik" },
  { value: "Aurangabad", label: "Aurangabad" },
  { value: "Delhi", label: "Delhi" },
  { value: "New Delhi", label: "New Delhi" },
  { value: "Gurugram", label: "Gurugram" },
  { value: "Noida", label: "Noida" },
  { value: "Faridabad", label: "Faridabad" },
  { value: "Bengaluru", label: "Bengaluru" },
  { value: "Mysuru", label: "Mysuru" },
  { value: "Mangalore", label: "Mangalore" },
  { value: "Chennai", label: "Chennai" },
  { value: "Coimbatore", label: "Coimbatore" },
  { value: "Madurai", label: "Madurai" },
  { value: "Hyderabad", label: "Hyderabad" },
  { value: "Visakhapatnam", label: "Visakhapatnam" },
  { value: "Vijayawada", label: "Vijayawada" },
  { value: "Kolkata", label: "Kolkata" },
  { value: "Howrah", label: "Howrah" },
  { value: "Chandigarh", label: "Chandigarh" },
  { value: "Mohali", label: "Mohali" },
  { value: "Jaipur", label: "Jaipur" },
  { value: "Udaipur", label: "Udaipur" },
  { value: "Ahmedabad", label: "Ahmedabad" },
  { value: "Surat", label: "Surat" },
  { value: "Vadodara", label: "Vadodara" },
  { value: "Lucknow", label: "Lucknow" },
  { value: "Kanpur", label: "Kanpur" },
  { value: "Indore", label: "Indore" },
  { value: "Bhopal", label: "Bhopal" },
  { value: "Patna", label: "Patna" },
  { value: "Ranchi", label: "Ranchi" },
  { value: "Bhubaneswar", label: "Bhubaneswar" },
  { value: "Cuttack", label: "Cuttack" },
  { value: "Kochi", label: "Kochi" },
  { value: "Thiruvananthapuram", label: "Thiruvananthapuram" },
  { value: "Trichy", label: "Trichy" },
  { value: "Goa", label: "Goa" },
  { value: "Remote", label: "Remote"}
];

export const jobCategories = [
  { value: "Information Technology", label: "Information Technology" },
  { value: "Software Development", label: "Software Development" },
  { value: "Web & Mobile App Development", label: "Web & Mobile App Development" },
  { value: "Data Science & Analytics", label: "Data Science & Analytics" },
  { value: "Cybersecurity", label: "Cybersecurity" },
  { value: "Cloud Computing & DevOps", label: "Cloud Computing & DevOps" },
  { value: "AI & Machine Learning", label: "AI & Machine Learning" },
  { value: "BPO / KPO / Customer Support", label: "BPO / KPO / Customer Support" },
  { value: "Sales & Business Development", label: "Sales & Business Development" },
  { value: "Digital Marketing & SEO", label: "Digital Marketing & SEO" },
  { value: "Content Writing & Editing", label: "Content Writing & Editing" },
  { value: "Graphic Design & UI/UX", label: "Graphic Design & UI/UX" },
  { value: "Finance & Accounting", label: "Finance & Accounting" },
  { value: "Banking & Insurance", label: "Banking & Insurance" },
  { value: "Chartered Accountancy", label: "Chartered Accountancy" },
  { value: "Human Resources & Recruitment", label: "Human Resources & Recruitment" },
  { value: "Engineering (Mechanical, Civil, Electrical)", label: "Engineering (Mechanical, Civil, Electrical)" },
  { value: "Architecture & Interior Design", label: "Architecture & Interior Design" },
  { value: "Construction & Real Estate", label: "Construction & Real Estate" },
  { value: "Education & Teaching", label: "Education & Teaching" },
  { value: "Healthcare & Nursing", label: "Healthcare & Nursing" },
  { value: "Pharmaceuticals & Biotech", label: "Pharmaceuticals & Biotech" },
  { value: "Hospitality & Tourism", label: "Hospitality & Tourism" },
  { value: "Retail & E-commerce", label: "Retail & E-commerce" },
  { value: "Manufacturing & Production", label: "Manufacturing & Production" },
  { value: "Logistics & Supply Chain", label: "Logistics & Supply Chain" },
  { value: "Transport & Delivery", label: "Transport & Delivery" },
  { value: "Legal & Compliance", label: "Legal & Compliance" },
  { value: "Media & Entertainment", label: "Media & Entertainment" },
  { value: "Film & Video Production", label: "Film & Video Production" },
  { value: "Sports & Fitness", label: "Sports & Fitness" },
  { value: "Government & Public Sector", label: "Government & Public Sector" },
  { value: "NGOs & Social Work", label: "NGOs & Social Work" }
];

export const jobTypes = [
  { value: "Full-time", label: "Full-time" },
  { value: "Part-time", label: "Part-time" },
  { value: "Contract", label: "Contract" },
  { value: "Internship", label: "Internship" },
  { value: "Remote", label: "Remote" },
];

